spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
