spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.1
          zkNodes: 192.168.99.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-school:8761/eureka/  
