spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-school:8761/eureka/  
